// js/data.js - All 56 Apify Actors

const actors = [
  // YouTube & Video Tools (6)
  {
    id: "youtube-transcript-scraper",
    name: "YouTube Transcript Scraper",
    category: "YouTube & Video Tools",
    categoryId: "youtube",
    description: "Scrape YouTube transcripts with 99%+ accuracy. Supports videos, shorts, and ended live streams",
    shortDescription: "Scrape YouTube transcripts with 99%+ accuracy",
    users: 275,
    rating: 5.0,
    totalRuns: 652510,
    apifyUrl: "https://apify.com/akash9078/youtube-transcript-extractor",
    icon: "📺",
    color: "#FF0000",
    features: ["99%+ accuracy", "Supports shorts", "Live streams"],
    useCases: ["Content analysis", "Research", "Subtitles"]
  },
  {
    id: "youtube-full-channel-transcripts",
    name: "YouTube Full Channel Transcripts",
    category: "YouTube & Video Tools",
    categoryId: "youtube",
    description: "Extract transcripts from all videos in a channel or individual videos",
    shortDescription: "Extract all transcripts from YouTube channels",
    users: 44,
    rating: null,
    totalRuns: 5000,
    apifyUrl: "https://apify.com/akash9078/youtube-full-channel-transcripts-extractor",
    icon: "📺",
    color: "#FF0000",
    features: ["Channel-wide extraction", "Individual videos", "Bulk processing"],
    useCases: ["Content archiving", "Research", "Analysis"]
  },
  {
    id: "youtube-channel-scraper",
    name: "YouTube Channel Scraper",
    category: "YouTube & Video Tools",
    categoryId: "youtube",
    description: "Scrape latest videos, shorts, and live streams with views and duration",
    shortDescription: "Scrape YouTube channel videos, shorts, live streams",
    users: 67,
    rating: 5.0,
    totalRuns: 1264,
    apifyUrl: "https://apify.com/akash9078/youtube-channel-video-scraper",
    icon: "📺",
    color: "#FF0000",
    features: ["Videos & shorts", "Live streams", "View counts"],
    useCases: ["Channel monitoring", "Analytics", "Research"]
  },
  {
    id: "youtube-playlist-scraper",
    name: "YouTube Playlist Scraper",
    category: "YouTube & Video Tools",
    categoryId: "youtube",
    description: "Extract video data from playlists including metadata and statistics",
    shortDescription: "Extract video data from YouTube playlists",
    users: 4,
    rating: null,
    totalRuns: 100,
    apifyUrl: "https://apify.com/akash9078/youtube-playlist-scraper",
    icon: "📺",
    color: "#FF0000",
    features: ["Playlist extraction", "Metadata", "Statistics"],
    useCases: ["Playlist analysis", "Content curation"]
  },
  {
    id: "youtube-playlist-with-transcript",
    name: "YouTube Playlist with Transcript",
    category: "YouTube & Video Tools",
    categoryId: "youtube",
    description: "Playlist scraper with transcript extraction capabilities",
    shortDescription: "Scrape playlists with transcripts",
    users: 3,
    rating: null,
    totalRuns: 50,
    apifyUrl: "https://apify.com/akash9078/youtube-playlist-scraper-with-transcript",
    icon: "📺",
    color: "#FF0000",
    features: ["Transcript extraction", "Playlist data", "Batch processing"],
    useCases: ["Content research", "Analysis"]
  },
  {
    id: "youtube-search-scraper",
    name: "YouTube Search Scraper",
    category: "YouTube & Video Tools",
    categoryId: "youtube",
    description: "Search YouTube via official Data API with structured results",
    shortDescription: "Search YouTube with structured results",
    users: 4,
    rating: null,
    totalRuns: 200,
    apifyUrl: "https://apify.com/akash9078/youtube-search-scraper",
    icon: "📺",
    color: "#FF0000",
    features: ["Official API", "Structured results", "Search queries"],
    useCases: ["Video discovery", "Research"]
  },

  // AI & LLM Tools (11)
  {
    id: "analyze-image",
    name: "Analyze Image",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "AI-powered image analysis - detect objects, styles, colors, emotions",
    shortDescription: "AI-powered image analysis and detection",
    users: 28,
    rating: 5.0,
    totalRuns: 800,
    apifyUrl: "https://apify.com/akash9078/analyze-image",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Object detection", "Style analysis", "Emotion detection"],
    useCases: ["Image analysis", "Content moderation"]
  },
  {
    id: "face-quality-enhancer",
    name: "Face Quality Enhancer",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "AI Image Upscaler - transform low-res images into high-quality visuals",
    shortDescription: "AI image upscaler for face enhancement",
    users: 83,
    rating: 5.0,
    totalRuns: 42606,
    apifyUrl: "https://apify.com/akash9078/ai-image-upscaler",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Face enhancement", "Image upscaling", "Quality improvement"],
    useCases: ["Photo enhancement", "Profile pictures"]
  },
  {
    id: "content-humanizer",
    name: "Content Humanizer",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "Transform AI-generated text into natural, human-like content",
    shortDescription: "Make AI text sound human",
    users: 104,
    rating: 5.0,
    totalRuns: 529,
    apifyUrl: "https://apify.com/akash9078/ai-content-humanizer",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Human-like text", "AI detection evasion", "Natural flow"],
    useCases: ["Content writing", "SEO content"]
  },
  {
    id: "free-kimi-2-5-api",
    name: "Free Kimi 2.5 API",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "Secure, scalable LLM API access through unified gateway",
    shortDescription: "Free access to Kimi 2.5 LLM API",
    users: 102,
    rating: 5.0,
    totalRuns: 272,
    apifyUrl: "https://apify.com/akash9078/free-kimi-2-5-api",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Free API access", "Scalable", "Secure"],
    useCases: ["LLM integration", "Text generation"]
  },
  {
    id: "face-swap",
    name: "Face Swap",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "AI face swapping between images using deep learning",
    shortDescription: "AI face swapping for images",
    users: 54,
    rating: 5.0,
    totalRuns: 1255,
    apifyUrl: "https://apify.com/akash9078/ai-face-swap",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Deep learning", "Face detection", "High quality"],
    useCases: ["Entertainment", "Creative projects"]
  },
  {
    id: "ai-image-generator",
    name: "AI Image Generator",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "Generate stunning AI images from text prompts",
    shortDescription: "Generate images from text",
    users: 9,
    rating: null,
    totalRuns: 300,
    apifyUrl: "https://apify.com/akash9078/ai-image-generator",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Text-to-image", "High quality", "Custom prompts"],
    useCases: ["Content creation", "Design"]
  },
  {
    id: "ai-travel-planner",
    name: "AI Travel Planner",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "AI-powered travel itineraries with web research via Mistral",
    shortDescription: "AI travel itinerary planning",
    users: 8,
    rating: null,
    totalRuns: 150,
    apifyUrl: "https://apify.com/akash9078/ai-travel-planner",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Web research", "Itinerary generation", "Mistral AI"],
    useCases: ["Travel planning", "Trip research"]
  },
  {
    id: "ai-codebase-analyst",
    name: "AI Codebase Analyst",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "GitHub repo analysis with intelligent insights & Q&A",
    shortDescription: "Analyze GitHub repos with AI",
    users: 2,
    rating: null,
    totalRuns: 50,
    apifyUrl: "https://apify.com/akash9078/ai-codebase-analyst",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Code analysis", "Q&A", "Insights"],
    useCases: ["Code review", "Documentation"]
  },
  {
    id: "ollama-mcp-server",
    name: "Ollama MCP Server",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "LLM actor supporting Llama 4, Vision models, protein folding",
    shortDescription: "Multi-model LLM server",
    users: 1,
    rating: null,
    totalRuns: 20,
    apifyUrl: "https://apify.com/akash9078/ollama-mcp-server",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Llama 4", "Vision models", "Multi-purpose"],
    useCases: ["LLM hosting", "AI applications"]
  },
  {
    id: "creative-content-generator",
    name: "Creative Content Generator",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "Generate stories, lyrics, rhymes, scripts, marketing content",
    shortDescription: "Generate creative content",
    users: 3,
    rating: null,
    totalRuns: 80,
    apifyUrl: "https://apify.com/akash9078/creative-content-generator",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Stories", "Lyrics", "Scripts", "Marketing"],
    useCases: ["Content creation", "Marketing"]
  },
  {
    id: "hn-ai-researcher",
    name: "HackerNews AI Researcher",
    category: "AI & LLM Tools",
    categoryId: "ai",
    description: "AI-powered tech trend analysis using NVIDIA AI",
    shortDescription: "Analyze HN trends with AI",
    users: 2,
    rating: null,
    totalRuns: 40,
    apifyUrl: "https://apify.com/akash9078/hn-ai-researcher",
    icon: "🤖",
    color: "#8B5CF6",
    features: ["Trend analysis", "NVIDIA AI", "HackerNews"],
    useCases: ["Tech research", "Trend monitoring"]
  },

  // Maps & Location Data (2)
  {
    id: "google-maps-scraper",
    name: "Google Maps Scraper",
    category: "Maps & Location Data",
    categoryId: "maps",
    description: "Extract business data, contact info, ratings & reviews",
    shortDescription: "Scrape Google Maps business data",
    users: 20,
    rating: 4.17,
    totalRuns: 800,
    apifyUrl: "https://apify.com/akash9078/google-maps-scraper",
    icon: "🗺️",
    color: "#10B981",
    features: ["Business data", "Contact info", "Reviews"],
    useCases: ["Lead generation", "Market research"]
  },
  {
    id: "google-maps-scraper-api",
    name: "Google Maps Scraper API",
    category: "Maps & Location Data",
    categoryId: "maps",
    description: "Official Google Places API integration for business data",
    shortDescription: "Official API for Maps data",
    users: 16,
    rating: null,
    totalRuns: 400,
    apifyUrl: "https://apify.com/akash9078/google-maps-scraper-api",
    icon: "🗺️",
    color: "#10B981",
    features: ["Official API", "Places data", "Reliable"],
    useCases: ["Business data", "Location services"]
  },

  // Search & SEO (6)
  {
    id: "google-serp-scraper",
    name: "Google SERP Scraper",
    category: "Search & SEO",
    categoryId: "seo",
    description: "Extract organic search results with SERP proxy",
    shortDescription: "Scrape Google search results",
    users: 13,
    rating: null,
    totalRuns: 500,
    apifyUrl: "https://apify.com/akash9078/google-serp-scraper",
    icon: "🔍",
    color: "#3B82F6",
    features: ["SERP extraction", "Proxy support", "Organic results"],
    useCases: ["SEO analysis", "Rank tracking"]
  },
  {
    id: "google-trends-scraper",
    name: "Google Trends Scraper",
    category: "Search & SEO",
    categoryId: "seo",
    description: "Extract trending searches with volume & growth metrics",
    shortDescription: "Scrape Google Trends data",
    users: 15,
    rating: null,
    totalRuns: 600,
    apifyUrl: "https://apify.com/akash9078/google-trends-scraper",
    icon: "🔍",
    color: "#3B82F6",
    features: ["Trending searches", "Volume data", "Growth metrics"],
    useCases: ["Trend analysis", "Market research"]
  },
  {
    id: "keyword-suggestion-generator",
    name: "Keyword Suggestion Generator",
    category: "Search & SEO",
    categoryId: "seo",
    description: "Generate keywords from Google/YouTube/Amazon/Bing",
    shortDescription: "Generate keyword suggestions",
    users: 12,
    rating: null,
    totalRuns: 450,
    apifyUrl: "https://apify.com/akash9078/keyword-suggestion-generator",
    icon: "🔍",
    color: "#3B82F6",
    features: ["Multi-platform", "Suggestions", "SEO"],
    useCases: ["Keyword research", "SEO optimization"]
  },
  {
    id: "web-search-scraper",
    name: "Web Search Scraper",
    category: "Search & SEO",
    categoryId: "seo",
    description: "Real-time search results API with comprehensive snippets",
    shortDescription: "Real-time web search API",
    users: 22,
    rating: null,
    totalRuns: 900,
    apifyUrl: "https://apify.com/akash9078/web-search-scraper",
    icon: "🔍",
    color: "#3B82F6",
    features: ["Real-time", "API access", "Comprehensive"],
    useCases: ["Search integration", "Data extraction"]
  },
  {
    id: "google-news-scraper",
    name: "Google News Scraper",
    category: "Search & SEO",
    categoryId: "seo",
    description: "Lightweight Google News API with structured results",
    shortDescription: "Scrape Google News articles",
    users: 23,
    rating: null,
    totalRuns: 950,
    apifyUrl: "https://apify.com/akash9078/google-news-scraper",
    icon: "🔍",
    color: "#3B82F6",
    features: ["News extraction", "Structured data", "Lightweight"],
    useCases: ["News monitoring", "Research"]
  },
  {
    id: "reddit-scraper",
    name: "Reddit Scraper",
    category: "Search & SEO",
    categoryId: "seo",
    description: "Find Reddit discussions by keyword with post details",
    shortDescription: "Search Reddit by keyword",
    users: 9,
    rating: null,
    totalRuns: 350,
    apifyUrl: "https://apify.com/akash9078/reddit-scraper",
    icon: "🔍",
    color: "#3B82F6",
    features: ["Keyword search", "Post details", "Discussions"],
    useCases: ["Social listening", "Research"]
  },

  // E-commerce (6)
  {
    id: "amazon-product-scraper",
    name: "Amazon Product Scraper",
    category: "E-commerce",
    categoryId: "ecommerce",
    description: "Extract product data, pricing, ratings, reviews",
    shortDescription: "Scrape Amazon product data",
    users: 24,
    rating: null,
    totalRuns: 800,
    apifyUrl: "https://apify.com/akash9078/amazon-product-scraper",
    icon: "🛒",
    color: "#F59E0B",
    features: ["Product data", "Pricing", "Reviews"],
    useCases: ["Price monitoring", "Competitor analysis"]
  },
  {
    id: "amazon-search-scraper",
    name: "Amazon Search Scraper",
    category: "E-commerce",
    categoryId: "ecommerce",
    description: "Scrape products from Amazon search results",
    shortDescription: "Scrape Amazon search results",
    users: 16,
    rating: null,
    totalRuns: 550,
    apifyUrl: "https://apify.com/akash9078/amazon-search-scraper",
    icon: "🛒",
    color: "#F59E0B",
    features: ["Search results", "Product listings", "Data"],
    useCases: ["Product research", "Market analysis"]
  },
  {
    id: "etsy-product-scraper",
    name: "Etsy Product Scraper",
    category: "E-commerce",
    categoryId: "ecommerce",
    description: "Scrape product data from Etsy.com",
    shortDescription: "Scrape Etsy product data",
    users: 43,
    rating: null,
    totalRuns: 1400,
    apifyUrl: "https://apify.com/akash9078/etsy-product-scraper",
    icon: "🛒",
    color: "#F59E0B",
    features: ["Product details", "Images", "Pricing"],
    useCases: ["Market research", "Product analysis"]
  },
  {
    id: "etsy-store-scraper",
    name: "Etsy Store Scraper",
    category: "E-commerce",
    categoryId: "ecommerce",
    description: "Scrape store listings, ratings, reviews",
    shortDescription: "Scrape Etsy store data",
    users: 25,
    rating: null,
    totalRuns: 700,
    apifyUrl: "https://apify.com/akash9078/etsy-store-scraper",
    icon: "🛒",
    color: "#F59E0B",
    features: ["Store data", "Ratings", "Reviews"],
    useCases: ["Store analysis", "Competitor research"]
  },
  {
    id: "made-in-china-scraper",
    name: "Made In China Scraper",
    category: "E-commerce",
    categoryId: "ecommerce",
    description: "Supplier product data extraction with certifications",
    shortDescription: "Scrape Made-in-China suppliers",
    users: 6,
    rating: null,
    totalRuns: 200,
    apifyUrl: "https://apify.com/akash9078/made-in-china-scraper",
    icon: "🛒",
    color: "#F59E0B",
    features: ["Supplier data", "Certifications", "Products"],
    useCases: ["Sourcing", "Supplier research"]
  },
  {
    id: "import-export-leads-finder",
    name: "Import Export Leads Finder",
    category: "E-commerce",
    categoryId: "ecommerce",
    description: "Global B2B import/export leads by country",
    shortDescription: "Find import/export leads",
    users: 8,
    rating: null,
    totalRuns: 280,
    apifyUrl: "https://apify.com/akash9078/import-export-leads-finder",
    icon: "🛒",
    color: "#F59E0B",
    features: ["B2B leads", "Global data", "By country"],
    useCases: ["Lead generation", "B2B sales"]
  },

  // Crypto & Finance (5)
  {
    id: "indian-stocks-financial-data",
    name: "Indian Stocks Financial Data",
    category: "Crypto & Finance",
    categoryId: "crypto",
    description: "Scrape P/E, ROE, ROCE, SALES, ratios & financials",
    shortDescription: "Scrape Indian stock financials",
    users: 61,
    rating: null,
    totalRuns: 5191,
    apifyUrl: "https://apify.com/akash9078/indian-stocks-financial-data-scraper",
    icon: "💰",
    color: "#F97316",
    features: ["P/E ratio", "ROE", "ROCE", "Financials"],
    useCases: ["Stock analysis", "Investment research"]
  },
  {
    id: "crypto-price-api",
    name: "Crypto Price API",
    category: "Crypto & Finance",
    categoryId: "crypto",
    description: "Live Bitcoin & altcoin prices with TA (RSI, MACD, etc.)",
    shortDescription: "Live crypto prices with TA",
    users: 4,
    rating: null,
    totalRuns: 150,
    apifyUrl: "https://apify.com/akash9078/crypto-price-api",
    icon: "💰",
    color: "#F97316",
    features: ["Live prices", "Technical analysis", "Bitcoin"],
    useCases: ["Trading", "Price monitoring"]
  },
  {
    id: "coinbase-market-data-api",
    name: "Coinbase Market Data API",
    category: "Crypto & Finance",
    categoryId: "crypto",
    description: "Real-time crypto ticker, OHLCV, order book",
    shortDescription: "Coinbase market data API",
    users: 2,
    rating: null,
    totalRuns: 80,
    apifyUrl: "https://apify.com/akash9078/coinbase-market-data-api",
    icon: "💰",
    color: "#F97316",
    features: ["Real-time", "OHLCV", "Order book"],
    useCases: ["Trading data", "Market analysis"]
  },
  {
    id: "new-listed-crypto-coins",
    name: "New Listed Crypto Coins",
    category: "Crypto & Finance",
    categoryId: "crypto",
    description: "Scrape newly listed tokens/coins for alerts",
    shortDescription: "Track new crypto listings",
    users: 2,
    rating: null,
    totalRuns: 70,
    apifyUrl: "https://apify.com/akash9078/new-listed-crypto-coins-scraper",
    icon: "💰",
    color: "#F97316",
    features: ["New listings", "Token alerts", "Tracking"],
    useCases: ["Trading", "Investment"]
  },
  {
    id: "exchangerate-api",
    name: "ExchangeRate API",
    category: "Crypto & Finance",
    categoryId: "crypto",
    description: "Real-time currency exchange rates",
    shortDescription: "Currency exchange rates API",
    users: 2,
    rating: null,
    totalRuns: 60,
    apifyUrl: "https://apify.com/akash9078/exchangerate-api",
    icon: "💰",
    color: "#F97316",
    features: ["Real-time rates", "Multiple currencies", "API"],
    useCases: ["Forex", "Currency conversion"]
  },

  // Image & Media Tools (7)
  {
    id: "pdf-text-extractor",
    name: "Extract Text from PDF",
    category: "Image & Media Tools",
    categoryId: "media",
    description: "PDF text extraction for data processing workflows",
    shortDescription: "Extract text from PDF files",
    users: 57,
    rating: null,
    totalRuns: 1409,
    apifyUrl: "https://apify.com/akash9078/pdf-text-extractor",
    icon: "🎨",
    color: "#EC4899",
    features: ["Text extraction", "PDF processing", "Data workflows"],
    useCases: ["Document processing", "Data extraction"]
  },
  {
    id: "image-format-converter",
    name: "Image Format Converter",
    category: "Image & Media Tools",
    categoryId: "media",
    description: "Convert JPG, PNG, WebP, AVIF, GIF, BMP, TIFF",
    shortDescription: "Convert image formats",
    users: 39,
    rating: null,
    totalRuns: 950,
    apifyUrl: "https://apify.com/akash9078/image-format-converter",
    icon: "🎨",
    color: "#EC4899",
    features: ["Multiple formats", "JPG", "PNG", "WebP", "AVIF"],
    useCases: ["Image conversion", "Web optimization"]
  },
  {
    id: "image-pdf-converter",
    name: "Image ↔ PDF Converter",
    category: "Image & Media Tools",
    categoryId: "media",
    description: "Bidirectional image-PDF conversion",
    shortDescription: "Convert images to/from PDF",
    users: 27,
    rating: null,
    totalRuns: 650,
    apifyUrl: "https://apify.com/akash9078/image-pdf-converter",
    icon: "🎨",
    color: "#EC4899",
    features: ["Bidirectional", "Image to PDF", "PDF to image"],
    useCases: ["Document creation", "Image extraction"]
  },
  {
    id: "frame-image-converter",
    name: "Convert Image Aspect Ratio",
    category: "Image & Media Tools",
    categoryId: "media",
    description: "Transform images to custom aspect ratios",
    shortDescription: "Change image aspect ratios",
    users: 10,
    rating: 5.0,
    totalRuns: 300,
    apifyUrl: "https://apify.com/akash9078/frame-image-converter",
    icon: "🎨",
    color: "#EC4899",
    features: ["Custom ratios", "Aspect transformation", "Resizing"],
    useCases: ["Social media", "Design"]
  },
  {
    id: "audio-file-converter",
    name: "Audio Format Converter",
    category: "Image & Media Tools",
    categoryId: "media",
    description: "MP3, WAV, FLAC, OGG, AMR, OPUS, AAC, M4A, WebM",
    shortDescription: "Convert audio formats",
    users: 107,
    rating: 5.0,
    totalRuns: 1599,
    apifyUrl: "https://apify.com/akash9078/audio-file-converter",
    icon: "🎨",
    color: "#EC4899",
    features: ["Multiple formats", "MP3", "WAV", "FLAC", "OGG"],
    useCases: ["Audio conversion", "Format compatibility"]
  },
  {
    id: "website-screenshot-generator",
    name: "Website Screenshot Generator",
    category: "Image & Media Tools",
    categoryId: "media",
    description: "Capture webpage screenshots with scheduling",
    shortDescription: "Generate website screenshots",
    users: 52,
    rating: null,
    totalRuns: 1664,
    apifyUrl: "https://apify.com/akash9078/website-screenshot-generator",
    icon: "🎨",
    color: "#EC4899",
    features: ["Screenshots", "Scheduling", "Web capture"],
    useCases: ["Monitoring", "Archiving", "Testing"]
  },
  {
    id: "advanced-text-to-speech",
    name: "Text to Speech Generator",
    category: "Image & Media Tools",
    categoryId: "media",
    description: "AI-powered TTS with 50+ voices, 9 languages",
    shortDescription: "Convert text to speech",
    users: 18,
    rating: null,
    totalRuns: 500,
    apifyUrl: "https://apify.com/akash9078/advanced-text-to-speech",
    icon: "🎨",
    color: "#EC4899",
    features: ["50+ voices", "9 languages", "AI-powered"],
    useCases: ["Voiceover", "Accessibility", "Content"]
  },

  // Social Media (4)
  {
    id: "tiktok-scraper",
    name: "TikTok Scraper",
    category: "Social Media",
    categoryId: "social",
    description: "Video metadata extraction from user profiles",
    shortDescription: "Scrape TikTok profile data",
    users: 2,
    rating: null,
    totalRuns: 50,
    apifyUrl: "https://apify.com/akash9078/tiktok-scraper",
    icon: "📱",
    color: "#06B6D4",
    features: ["Profile data", "Video metadata", "Extraction"],
    useCases: ["Influencer research", "Content analysis"]
  },
  {
    id: "tiktok-trending-hashtags",
    name: "TikTok Trending Hashtags",
    category: "Social Media",
    categoryId: "social",
    description: "Extract top 100 trending hashtags with metrics",
    shortDescription: "Scrape TikTok trending hashtags",
    users: 2,
    rating: null,
    totalRuns: 40,
    apifyUrl: "https://apify.com/akash9078/tiktok-trending-hashtags-scraper",
    icon: "📱",
    color: "#06B6D4",
    features: ["Top 100", "Trending", "Metrics"],
    useCases: ["Trend analysis", "Marketing"]
  },
  {
    id: "x-trending-scraper",
    name: "X (Twitter) Trending Topics",
    category: "Social Media",
    categoryId: "social",
    description: "Scrape trending hashtags from X.com",
    shortDescription: "Scrape X trending topics",
    users: 4,
    rating: null,
    totalRuns: 120,
    apifyUrl: "https://apify.com/akash9078/x-trending-scraper",
    icon: "📱",
    color: "#06B6D4",
    features: ["Trending hashtags", "X.com", "Topics"],
    useCases: ["Social listening", "Trends"]
  },
  {
    id: "facebook-ad-library-scraper",
    name: "Facebook Ad Library Scraper",
    category: "Social Media",
    categoryId: "social",
    description: "Extract ad creatives, targeting, performance",
    shortDescription: "Scrape Facebook ad data",
    users: 2,
    rating: null,
    totalRuns: 60,
    apifyUrl: "https://apify.com/akash9078/facebook-ad-library-scraper",
    icon: "📱",
    color: "#06B6D4",
    features: ["Ad creatives", "Targeting", "Performance"],
    useCases: ["Ad research", "Competitor analysis"]
  },

// Developer Tools & APIs (8)
{
id: "airbnb-destinations-scraper",
    name: "Airbnb Destinations Scraper",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "Scrape Airbnb listings with prices, amenities, reviews",
    shortDescription: "Scrape Airbnb destination data",
    users: 2,
    rating: null,
    totalRuns: 60,
    apifyUrl: "https://apify.com/akash9078/airbnb-destinations-scraper",
    icon: "🔧",
    color: "#6366F1",
    features: ["Listings", "Prices", "Amenities", "Reviews"],
    useCases: ["Travel research", "Market analysis"]
  },
  {
    id: "nasa-reports-scraper",
    name: "NASA Reports Scraper",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "Technical reports from NASA Technical Reports Server",
    shortDescription: "Scrape NASA technical reports",
    users: 2,
    rating: null,
    totalRuns: 40,
    apifyUrl: "https://apify.com/akash9078/nasa-reports-scraper",
    icon: "🔧",
    color: "#6366F1",
    features: ["Technical reports", "NASA", "Research"],
    useCases: ["Research", "Space data"]
  },
  {
    id: "huggingface-model-page-scraper",
    name: "HuggingFace Model Scraper",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "Scrape model metadata & model cards",
    shortDescription: "Scrape HuggingFace model data",
    users: 2,
    rating: null,
    totalRuns: 50,
    apifyUrl: "https://apify.com/akash9078/huggingface-model-page-scraper",
    icon: "🔧",
    color: "#6366F1",
    features: ["Model metadata", "Model cards", "AI"],
    useCases: ["AI research", "Model discovery"]
  },
  {
    id: "air-quality-index-aqi-api",
    name: "Air Quality Index (AQI) API",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "PM2.5, PM10, CO, weather + AI health recommendations",
    shortDescription: "Air quality data API",
    users: 2,
    rating: null,
    totalRuns: 70,
    apifyUrl: "https://apify.com/akash9078/air-quality-index-aqi-api",
    icon: "🔧",
    color: "#6366F1",
    features: ["PM2.5", "PM10", "CO", "Weather", "AI"],
    useCases: ["Health", "Environment"]
  },
  {
    id: "hsn-code-finder-india",
    name: "HSN Code Finder India",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "AI-powered product classification for Indian GST",
    shortDescription: "Find HSN codes for GST",
    users: 11,
    rating: null,
    totalRuns: 350,
    apifyUrl: "https://apify.com/akash9078/hsn-code-finder-india",
    icon: "🔧",
    color: "#6366F1",
    features: ["AI-powered", "GST", "HSN codes", "Classification"],
    useCases: ["Tax compliance", "E-commerce"]
  },
  {
    id: "daily-horoscope-api",
    name: "Daily Horoscope API",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "Horoscope predictions for all zodiac signs",
    shortDescription: "Daily horoscope predictions",
    users: 5,
    rating: null,
    totalRuns: 180,
    apifyUrl: "https://apify.com/akash9078/daily-horoscope-api",
    icon: "🔧",
    color: "#6366F1",
    features: ["Daily predictions", "Zodiac signs", "All signs"],
    useCases: ["Entertainment", "Apps"]
  },
  {
    id: "random-facts-api",
    name: "Random Facts API",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "Thousands of random facts & trivia",
    shortDescription: "Random facts and trivia API",
    users: 2,
    rating: null,
    totalRuns: 90,
    apifyUrl: "https://apify.com/akash9078/random-facts-api",
    icon: "🔧",
    color: "#6366F1",
    features: ["Random facts", "Trivia", "Thousands"],
    useCases: ["Education", "Entertainment"]
  },
  {
    id: "inspirational-quote-generator",
    name: "Inspirational Quote Generator",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "Generate motivational quotes with authors",
    shortDescription: "Generate inspirational quotes",
    users: 2,
    rating: null,
    totalRuns: 80,
    apifyUrl: "https://apify.com/akash9078/inspirational-quote-generator",
    icon: "🔧",
    color: "#6366F1",
    features: ["Motivational", "Quotes", "Authors"],
    useCases: ["Motivation", "Content"]
  },
  {
    id: "lorem-ipsum-text-generator",
    name: "Lorem Ipsum Generator",
    category: "Developer Tools & APIs",
    categoryId: "dev",
    description: "Configurable placeholder text generator",
    shortDescription: "Generate placeholder text",
    users: 3,
    rating: null,
    totalRuns: 100,
    apifyUrl: "https://apify.com/akash9078/lorem-ipsum-text-generator",
    icon: "🔧",
    color: "#6366F1",
    features: ["Placeholder text", "Configurable", "Lorem ipsum"],
    useCases: ["Design", "Development"]
  }
];

// Category definitions
const categories = [
  { id: "youtube", name: "YouTube & Video Tools", icon: "📺", color: "#FF0000", count: 6 },
  { id: "ai", name: "AI & LLM Tools", icon: "🤖", color: "#8B5CF6", count: 11 },
  { id: "maps", name: "Maps & Location Data", icon: "🗺️", color: "#10B981", count: 2 },
  { id: "seo", name: "Search & SEO", icon: "🔍", color: "#3B82F6", count: 6 },
  { id: "ecommerce", name: "E-commerce", icon: "🛒", color: "#F59E0B", count: 6 },
  { id: "crypto", name: "Crypto & Finance", icon: "💰", color: "#F97316", count: 5 },
  { id: "media", name: "Image & Media Tools", icon: "🎨", color: "#EC4899", count: 7 },
  { id: "social", name: "Social Media", icon: "📱", color: "#06B6D4", count: 4 },
  { id: "dev", name: "Developer Tools & APIs", icon: "🔧", color: "#6366F1", count: 10 }
];

// Statistics
const stats = {
  totalActors: 56,
  totalUsers: 1500,
  monthlyUsers: 468,
  successRate: 98.9,
  responseTime: 6,
  totalRuns: 1000000
};

// Calculate actual totals from data
stats.totalActors = actors.length;
stats.totalUsers = actors.reduce((sum, actor) => sum + actor.users, 0);
stats.totalRuns = actors.reduce((sum, actor) => sum + actor.totalRuns, 0);

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { actors, categories, stats };
}
